atm:
  money: 2000000
logging:
  level:
    root: info
  file:
    max-history: 10
    max-size: 5MB

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} - %msg%n'
    file: '%d{dd-MM-yyyy HH:mm:ss} - %msg%n'
  path: logs/simplelog

